app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('hello', function()
{  
	return View::make('hello'); //link login to backend
});

 Route::get('/', array('as' => 'index', 'uses' => 'HomeController@getIndex'));
 Route::get('logout', array('as' => 'login.logout', 'uses' => 'LoginController@getLogout'));
 Route::post('/support', array('as' => 'support', 'uses' => 'HomeController@postSupport'));
 Route::get('/denied', array('as' => 'access.denied', 'uses' => 'LoginController@getAccessDenied'));
 Route::post('login', array('as' => 'login.user', 'uses' => 'LoginController@postUserLogin'));
 Route::get('static/{alias}', array('as'=>'static', 'uses' =>'HomeController@getStatic')); 

 Route::get("search-extended", ["as" => "search.extended", "uses" => "SearchController@getExtendedSearchPage"]);
 Route::post("search-extended", ["as" => "search.extended", "uses" => "SearchController@postExtendedSearch"]);
 Route::get("search-result", ["as" => "search.result", "uses" => "SearchController@getSearchResult"]);
 Route::get("search", ["as" => "search.simple", "uses" => "SearchController@getSimpleSearchResults"]);


 //is not Auth
Route::group(array('before' => 'guest'), function(){
    Route::get('/teaser', array('as' => 'teaser', 'uses' => 'LoginController@getTeaser'));
    Route::get('/subscriptions', array('as' => 'choose.subscriptions', 'uses' => 'LoginController@getSubscriptions'));
    Route::get('/information', array('as' => 'login.yourinfo', 'uses' => 'LoginController@getYourInfo'));
    Route::post('/information', array('uses' => 'LoginController@postYourInfo'));
    
    Route::get('/password/remind', array('as' => 'password.lost', 'uses' => 'LoginController@getLostPassword'));
    Route::post('/password/remind', array('uses' => 'LoginController@postLostPassword'));
    Route::get('/password/thanks', array('as' => 'password.thanks', 'uses' => 'LoginController@getThanks'));
    Route::get("/password/reset/{token}", "LoginController@getResetUser");
    Route::post("/password/reset/{token}", "LoginController@postResetUser");
    
});
//guest or owner
Route::group(array('before' => 'auth.owner_or_guest'), function(){
    Route::get('/payment/method', array('as' => 'choose.payment', 'uses' => 'LoginController@getPaymentMethod'));
    Route::get('/payment/info', array('as' => 'choose.paymentInfo', 'uses' => 'LoginController@getCreditCardInfo'));
    Route::post('/payment/info', array('uses' => 'LoginController@postCreditCardInfo'));
    Route::get('/payment/receipt', array('as' => 'receipt', 'uses' => 'LoginController@getReceipt'));
});

// Any customer
Route::group(array('before' => 'auth.any_customer'), function(){
   // Route::get('/profile', array('as' => 'profile', 'uses' => 'ProfileController@getProfile'));
    Route::get('/profile', array('as' => 'profile', 
        function(){
          Alert::keep(true);
           if(Entrust::hasRole("customer"))
             return Redirect::route("profile.customer");
           elseif(Entrust::hasRole("company_owner"))
             return Redirect::route("profile.owner");
           else
             return Redirect::route("access.denied");
    }));    
    Route::get('/profile/password', array('as' => 'profile.password', 'uses' => 'ProfileController@getChangePassword'));
    Route::post('/profile/password', array('uses' => 'ProfileController@postChangePassword'));
    
    //DataBase
    Route::get('database', array('as' => 'db', 'uses' => 'DatabaseController@getIndex'));
    Route::get('database/topic/{id}', array('as' => 'db.topic', 'uses' => 'DatabaseController@getTopic'))->where('id', "[0-9]*");
    Route::get('ajax/tab/{id}', array('as' => 'ajax.tab', 'uses' => 'DatabaseController@getAjaxTab'))->where('id', "[0-9]*");
    Route::get('database/tag/{id}', array('as' => 'db.tag', 'uses' => 'DatabaseController@getTag'))->where('id', "[0-9]*");
    Route::get('database/content/{id}', array('as' => 'db.content', 'uses' => 'DatabaseController@getArticle'))->where('id', "[0-9]*");
});

//Profile  collegue customer
Route::group(array('before' => 'auth.customer'), function(){
    Route::get('/profile/customer', array('as' => 'profile.customer', 'uses' => 'ProfileController@getCustomer'));
});

//Paying customer - owner
Route::group(array('before' => 'auth.company_owner'), function()
{
    Route::get('/profile/owner', array('as' => 'profile.owner', 'uses' => 'ProfileController@getPayingOwner'));
    Route::post('/profile/owner', array('uses' => 'ProfileController@postPayingOwner'));
    Route::get('/profile/subscriptions', array('as' => 'profile.subscriptions', 'uses' => 'ProfileController@getSubscriptions'));
    Route::get('/profile/subscriptions/change', array('as' => 'profile.subscriptions.change', 'uses' => 'ProfileController@getChangeSubscrip'));
    Route::get('/profile/payments', array('as' => 'profile.payments', 'uses' => 'ProfileController@getPayments'));
    Route::get('/profile/users/add', array('as' => 'profile.add_users', 'uses' => 'ProfileController@getAddUsers'));
    Route::post('/profile/users/add', array('uses' => 'ProfileController@postAddUser'));
    Route::get('/profile/users/delete/{id}', array('as' => 'profile.del_user', 'uses' => 'ProfileController@getDeleteUser'))->where('id', "[0-9]*");
});

//admin login
Route::group(array("prefix" => "admin", 'before' => 'auth.adminlogin'), function()
{
   // Route::get("/", "HomeController@getIndex");
    
    Route::get('login', array('as' => 'login', 'uses' => 'LoginController@getLogin'));
    Route::get('register', array('as' => 'login.register', 'uses' => 'LoginController@getRegister'));
    Route::post('login', array('uses' => 'LoginController@postLogin'));
    Route::post('register', array('uses' => 'LoginController@postStore'));
 
    Route::get("/password/remind", array('as'=> 'password.remind', 'uses' => "LoginController@getRemind"));
    Route::post("/password/remind", "LoginController@postRemind");
    Route::get("/password/reset/{token}", "LoginController@getReset");
    Route::post("/password/reset/{token}", "LoginController@postReset");
});

//admins area
Route::group(["prefix" => "admin", "before" => "auth.admin"], function (){
       //users, staff
    Route::get("users/staff", array("as"=>"users.staff", "uses" => "AdminController@getStaff"));
    Route::get("users/addstaff", array('as'=>'users.addStaff' , "uses" =>"AdminController@getAddStaff"));
    Route::post("users/addstaff", array("uses" =>"AdminController@postAddStaff"));
    Route::get("users/delete", array('as'=>'users.delete' , "uses" =>"AdminController@getDeleteStaff"));  
    
    //Pricing
    //Route::get('prising', array('as'=>'pricing', 'uses' =>'AdminController@getPricing'));
    Route::get('prising/new', array('as'=>'pricing.new', 'uses' =>'AdminController@getPricingNew'));
    Route::post('prising/new', array('uses' =>'AdminController@postPricingNew'));
    Route::get('prising/edit', array('as'=>'pricing', 'uses' =>'AdminController@getPricingEdit'));
    Route::post('prising/edit', array( 'uses' =>'AdminController@postPricingEdit'));
    
    //Subscriptions
    Route::get('subscriptions', array('as'=>'subscriptions', 'uses' =>'AdminController@getSubscriptions'));
    Route::get('subscribers/browse', array('as'=>'subscribers.browse', 'uses' =>'AdminController@getSubscribers'));
    Route::get('subscribers/table', array('as'=>'subscribers.table', 'uses' =>'AdminController@getSubscribersJson'));
    Route::get('subscribers/edit', array('as'=>'subscribers.edit', 'uses' =>'AdminController@getEditSubscriber'));
    Route::post('subscribers/edit', array('uses' =>'AdminController@postEditSubscriber'));
    Route::get('subscribers/delete', array('as'=>'subscribers.delete', 'uses' =>'AdminController@getDeleteSubscr'));
    Route::get('subscribers/add', array('as'=>'subscribers.add', 'uses' =>'AdminController@getNewSubscriber'));
    Route::post('subscribers/add', array('uses' =>'AdminController@postNewSubscriber'));
    //Remind user password on subscriber
    Route::get('subscribers/password', array('as'=>'subscriber.password', 'uses' =>'AdminController@getSubscriberRemind'));
    Route::get('subscription/delete', array('as'=>'subscription.delete', 'uses' =>'AdminController@getSubscriptionDelete'));

    //payments
    Route::get('payments', array('as'=>'payments', 'uses' =>'AdminController@getPayments'));
    Route::post('payments', array('uses' =>'AdminController@postPayments'));

    //advertisements
    Route::get('advertisements', array('as'=>'advertisements', 'uses' =>'AdminController@getAdvertisements'));
    Route::post('advertisements', array('uses' =>'AdminController@postAdvertisements'));   

    //settings
    Route::get('settings', array('as'=>'settings', 'uses' =>'AdminController@getSettings'));
    Route::get('settings/edit', array('as'=>'settings.edit', 'uses' =>'AdminController@getEditSettings'));
    Route::post('settings/edit', array('uses' =>'AdminController@postEditSettings'));
    //Languages/translations
    Route::get('settings/translations', array('as'=>'settings.translations', 'uses' =>'AdminController@getTranslationsList'));
    //Route::get('settings/translations/new', array('as'=>'settings.translations.new', 'uses' =>'AdminController@getTranslationNew'));
    Route::get('settings/translations/edit', array('as'=>'settings.translations.edit', 'uses' =>'AdminController@getTranslationEdit'));
    Route::post('settings/translations/edit', array('as'=>'settings.translations.save', 'uses' =>'AdminController@postTranslationEdit'));
    Route::get('settings/translations/delete', array('as'=>'settings.translations.delete', 'uses' =>'AdminController@getTranslationDelete'));

app/models/Payment.php
<?php

class Payment extends BaseModel {

	public $timestamps = true;
 	//payment_status
    const STATUS_PAID = 'paid';
    const STATUS_PENDING = 'pending';
    const STATUS_EXCEEDED = 'exceeded';
    //payment_method
    const METHOD_CREDITCARD = 'creditcard';
    const METHOD_ONLINE_BANKING = 'online_banking';
    const METHOD_PAYMENT_SLIP = 'payment_slip';
    const METHOD_EAN = 'ean';
 	protected $fillable = ['invoice_number', 'billing_date', 'payment_due',
      'amount_vat', 'total_amount_due', 'card_number'];
    

    public static function getRules(){
        return array(
            'invoice_number'    => 'required|max:255',
            'billing_date'      =>  'date',//'date_format:d-m-Y',
            'payment_due'       =>  'date',
            'amount_vat'	    => 'required|numeric|min:0',
            'total_amount_due'	=> 'required|numeric|min:0'
        );
    }


	public function subscriberInfo()
	{
		return $this->belongsTo('SubscriberInfo');
	}
//  public static function getEmptyPayment(){
//    return new Payment;
//  }
  
  public function getStatus(){
    switch($this->payment_status){
      case Payment::STATUS_PAID:
        return t("profile.paid");
        break;
      case Payment::STATUS_PENDING:
//        return t("profile.pending");
//        break;                      
      case Payment::STATUS_EXCEEDED:
//        return t("profile.exceeded");
        return t("profile.not_paid");
        break;
    }
    return "";
  }
  
  public function getMethodPayment(){
    switch($this->payment_method){
      case Payment::METHOD_CREDITCARD:
        return t("registration.credit_card");
        break;
      case Payment::METHOD_ONLINE_BANKING:
        return t("registration.online_banking");
        break;                      
      case Payment::METHOD_PAYMENT_SLIP:
        return t("registration.payment_slip");
        break;
      case Payment::METHOD_EAN:
        return t("registration.ean_payment");
        break;
    }
    return "";
  }
  
  public function formatedCardNumber(){
    if(!$this->card_number)
      return "";
    $length = strlen($this->card_number);
    $formated = substr($this->card_number, -4);
    for($i=$length-5; $i>=0; $i--){
      if((($i+1) - $length) % 4 == 0){
        $formated = ' ' . $formated;
      }
      //put character to the begin
      $formated = $this->card_number[$i] . $formated;
    }
    return self::maskCreditCard($formated);
  }
  
  public static function maskCreditCard($cc){
    $length = strlen($cc);
    for($i=0; $i<$length-4; $i++){
      if($cc[$i] == ' '){
        continue;
      }
      $cc[$i] = 'X';
    }
    return $cc;
  }
}

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;
use Zizaco\Entrust\HasRole;

/**
 * User
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\Config::get('entrust::role[] $roles
 */
class User extends BaseModel implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait, HasRole;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	//protected $hidden = array('password', 'remember_token');
	protected $visible = array('name', 'email', 'initials');

	protected $fillable = array('name', 'initials', 'email', 'password', 'last_login', 'phone', 'occupation', 'optional');

	public static function getRules($isEmail = true)
	{
		$rules = array(
               'name'     	=> 'required|between:2,255', //|unique:users,name', //alpha_spaces|
               'initials' 	=> 'required|between:2,255', //alpha_spaces|
               //'email'    	=> 'required|email|max:255|unique:users,email',
               //'role'		=> 'required|numeric|min:1',
               'last_login' => 'date_format:d-m-Y H:i:s'
			);
		//'last_login' => 'date_format:d-m-Y H:i:s'
		if($isEmail)
			$rules["email"] = 'required|email|max:255|unique:users,email';
		return $rules;
	}
  
	public static function getOwnerRules($isPassword = true, $isEmail = true)
	{
		$rules =  array(
               'nameAdmin'     	=> 'required|between:2,255', 
               //'emailAdmin'     => 'required|email|max:255|unique:users,email',
           //  'password'       => 'required|confirmed',
			);
    if($isPassword)
      $rules["password"] = 'required|confirmed';
    if($isEmail)
      $rules["emailAdmin"] = 'required|email|max:255|unique:users,email';//$this->id,id
		return $rules;
	}
  public static function changePasswordRules(){
    return array(
        "old_password"  => "required",
        "password"  => "required|confirmed",
    );
  }
  
	public function customers(){
        return $this->belongsToMany(get_class($this), 'subscriber_customer', 'parent_user_id', 'user_id');
  }
  // id -> user_id - is this owner
  public function subscriberInfoOwner(){
      return $this->hasOne("SubscriberInfo");
  }
  
  // subscriber_info_id -> id - is this customer
  public function subscriberInfoCustomer(){
    return $this->belongsTo("SubscriberInfo", "subscriber_info_id");
  }
  
  public function getSubscriberInfoAttribute(){
    if($this->subscriberInfoOwner){
      return $this->subscriberInfoOwner;
    } else {
     return $this->subscriberInfoCustomer;
    }
  }
  
  public function saveUser($subscriber, $i = 1, $isOwner = false){
    $password = substr(md5(time() + $i), 0, 4);
    $this->password = Hash::make($password);
    $mail = $this->email;
    Mail::send("emails.createUser", [
         "login" => $this->email,
         "password" => $password
     ], function(\Illuminate\Mail\Message $message) use ($mail){
         $message->to($mail);
     });
     if($isOwner){
        $ownerRole = Role::where('name', '=', 'company_owner')->first();
        $ownerRole->users()->save($this);
        $subscriber->owner()->associate($this);
        $subscriber->save();
     } else{ 
        $customerRole = Role::where('name', '=', 'customer')->first();
        $customerRole->users()->save($this);
        $this->subscriberInfoCustomer()->associate($subscriber);
        $subscriber->customers()->save($this);
        $subscriber->owner->customers()->attach($this->id);
     }
  }
}

app/controllers/BaseFrontController.php
<?php

abstract class BaseFrontController extends BaseController {

  public function __construct(){
    parent::__construct();
    if (Request::isMethod('get')){
      //$this->setCaptcha();
      $this->setFrontMenu();
    }
  }

	protected function setCaptcha(){
		$captcha = App::make("Captcha");
		$this->viewData["captchaHtml"] = $captcha->Html();
	}
  
  protected function setFrontMenu(){
     $menu = StaticPage::with("trans")->where("show_in_top", "=", 1)
            ->orWhere("show_in_bottom", "=", 1)->orderBy("weight")->get();
     $topMenu = [];
     $bottomMenu = [];
     //$posPricing = 1;
     foreach($menu as $pos => $item){
       if($pos == 1){ // pos of pricing
         $topMenu[] = ["url" => "#", "title" => t("globals.menu.pricing")];//(not yet designed)
         $bottomMenu[] = ["url" => "#", "title" => t("globals.menu.pricing")];
       }
       if((bool)$item->show_in_top)
         $topMenu[] = ["url" => route("static", ["alias"=> $item->alias]), 
             "title" => $item->trans->title];
       if((bool)$item->show_in_bottom)
         $bottomMenu[] = ["url" => route("static", ["alias"=> $item->alias]), 
             "title" => $item->trans->title];       
     }
     $this->viewData["topMenu"] = $topMenu;
     $this->viewData["bottomMenu"] = $bottomMenu;
    //$this->viewData["activeMenu"]
  }

}

app/views/controllers/ProfileController/getChangePassword.blade.php
@extends("layouts.base")

@section("content")
  <div id="profile" class="container font-merriweather">
    <h4 class="spacer-1em">
      <b>{{ucfirst(t("profile.change_password"))}}</b>
    </h4>
    <div class="row">
      <div class="col-sm-8 line-2">
        {{t("profile.change_password_text")}}
      </div>
   </div>

   {{Form::open()}}
    <div class="form-group row spacer">
      <div class="col-sm-4">
          <label>{{t("profile.type_your_password")}}</label>
        {{--Form::password("old_password", ["class"=>"form-control", 
          "maxlength"=>"255", "required"=>"required"])--}}
  <input type="password" class="form-control"  required="required" name="old_password"
        maxlength="255" value="{{Input::old('old_password','')}}" />
      </div>
    </div>
    <div class="form-group row spacer-1em">
      <div class="col-sm-4">
          <label>{{t("profile.type_new_password")}}</label>
        <input type="password" class="form-control"  required="required" name="password"
        maxlength="255" value="{{Input::old('password','')}}" />          
      </div>
    </div>
    <div class="form-group row spacer-1em">
      <div class="col-sm-4">
          <label>{{t("profile.type_new_password_again")}}</label>
        <input type="password" class="form-control"  required="required"
               name="password_confirmation" maxlength="255" 
               value="{{Input::old('password_confirmation','')}}" /> 
      </div>
    </div>
    <div class="form-group row spacer-2em">
      <div class="col-sm-4">
          {{Form::submit(strtoupper(t("profile.change_password_button")), 
            ["class" => "btn btn-default font-proxima"])}}
      </div>
    </div>

   {{Form::close()}}
    
    
    <div class="spacer clearfix"></div>
    <div class="spacer clearfix"></div>
    <div class="spacer clearfix"></div>
    
  </div>
@stop

app/views/controllers/ProfileController/getChangeSubscrip.blade.php
@extends("layouts.base")

@section("content")
  <div class="container font-merriweather steps">
    <h4 class="spacer-1em">
      <b>{{ucfirst(t("profile.my_subscriptions"))}}</b>
    </h4>
    <div class="row">
      <div class="col-sm-8 line-2">
        {{t("profile.my_subscriptions_text")}}
      </div>
   </div>
    <div class="row spacer-2em">
      <div class="col-sm-8"><p><b>{{t("profile.current_subscription")}}</b></p></div>
    </div>
    <div class="row info-list spacer-05em">
     <div class="col-sm-8">
       <div class="row">
           <div class="col-xs-7 col-sm-4 text-center">
                <div class="width-auto text-center cross-line">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <span class="panel-title">{{$user->subscriber_info->subscription_name}}</span> 
                  </div>
                  <div class="panel-body">
                    <p>{{$user->subscriber_info->persons}} persones adgang</p>
                     <div class="spacer-1em clearfix"></div>
                    <p>{{$user->subscriber_info->price}} kr./md eksl. moms</p>
                    <div class="spacer clearfix"></div>
                  </div>
                </div>
                </div>
            </div>
          <div class="col-xs-6 col-sm-4 nowrap">
            {{ucfirst(t('validation.attributes.company_name'))}} <br />
            {{t("receipt.name_subscription")}} <br />
            {{t("receipt.license_number")}} <br />
            {{t("profile.number_users")}} <br />
            {{t("profile.next_payment")}} <br />
            {{t("profile.type_of_payment")}} <br />
            {{t("profile.card_number")}} <br />
          </div>
          <div class="col-xs-6 col-sm-4 text-right nowrap">
            @if($user->subscriber_info)
              {{ $user->subscriber_info->name }} <br />
              {{ $user->subscriber_info->subscription_name }} <br />
              {{ $user->subscriber_info->licens_number }} <br />
              {{ $user->subscriber_info->persons }} <br />
              @if($lastPayment)
                {{ date("d/m-y", strtotime($lastPayment->payment_due)) }} <br />
                {{ $lastPayment->getMethodPayment() }} <br />
                {{ $lastPayment->formatedCardNumber() }}
              @endif
            @endif
          </div>
       </div>
     </div>
    </div>
    <div class="row spacer-2em">
      <div class="col-sm-8"><b>{{t("profile.choose_new_subscription")}}</b> </div>
    </div> 
    <div class="row wrap spacer-05em" id="panel-btns">
      <div class="col-sm-8">
			   {{Form::open(["route"=>"choose.payment", "id"=>"chooseform", "method"=>"GET"])}}				
          @for($i=0, $count = $pricing->count(); $i < $count; )
				<div class="row">
            @for($j=0; $j<3 && $i<$count; $i++, $j++)
              <div class="col-sm-4">
                @if($pricing[$i]->id == $user->subscriber_info->subscriptionType->id)
                <div class="radio disabled">
                @else
                <div class="radio">
                @endif
                <label class="text-center">
                <div class="panel panel-default" id="{{'p' . $pricing[$i]->id}}">
                  <div class="panel-heading">
                    <span class="panel-title">{{$pricing[$i]->name}}</span> 
                  </div>
                  <div class="panel-body">
                    <p>{{$pricing[$i]->persons}} persones adgang</p>
                     <div class="spacer-1em clearfix"></div>
                    <p>{{$pricing[$i]->price}} kr./md eksl. moms</p>
                    <p class="spacer-1em text-center clearfix disabled">
                      @if($pricing[$i]->id == $user->subscriber_info->subscriptionType->id)
                        &nbsp;
                      @else
                        {{Form::radio("subscription_type_id", $pricing[$i]->id, false)}}
                      @endif
                    </p>
                    <div class="spacer clearfix"></div>
                  </div>
                    @if($pricing[$i]->id == $user->subscriber_info->subscriptionType->id)
                   <div class="cross"></div>
                   @endif
                </div>
                </label>
                </div>			
              </div>
            @endfor
				</div>
				  @endfor
				<div class="spacer clearfix"></div>				
				<button id="next" class="btn btn-default font-proxima pull-right" type="submit">
						<span>{{strtoupper(t("pagination.next"))}}</span></button>
				{{Form::close()}}
      </div>
    </div>
    <div class="spacer clearfix"></div>
    <div class="spacer clearfix"></div>
    <div class="spacer clearfix"></div>
    
  </div>
@stop

app/views/controllers/ProfileController/getCustomer.blade.php
@extends("layouts.base")

@section("content")
  <div id="profile" class="container font-merriweather">
    <h4 class="spacer-1em">
        <b>{{ucfirst(t("globals.menu.profile"))}}</b>
    </h4>
    <div class="row">
      <div class="col-sm-8 line-2">
        {{t("profile.colleague_profile_text")}}
      </div>
   </div>
    <div class="row spacer-1em">
      <div class="col-sm-8">
        <a href="{{route("profile.password")}}" class="btn btn-default font-proxima" role="button">
            {{strtoupper(t("profile.change_password"))}}</a>
        <a href="#" class="btn btn-default font-proxima" role="button">
            {{strtoupper(t("profile.my_saved_data"))}}</a>
        <div class="clearfix spacer-2em"></div>
        <div class="footer-line"></div>
      </div>
    </div>
    <div class="row spacer-1em info-list">
      <div class="col-sm-3 col-md-2">
          {{t("receipt.name_subscription")}} <br />
          {{t("receipt.license_number")}}
      </div>
        <div class="col-sm-3 col-md-3 text-right">
          @if($user->subscriber_info)
          {{ $user->subscriber_info->name }} <br />
          {{ $user->subscriber_info->licens_number }}
          @endif
        </div>
    </div>
    <div class="row spacer-1em">
      <div class="col-sm-4 form-group">
          <p>{{t("profile.my_information")}}</p>
        {{Form::text("name", $user->name, ["class"=>"form-control", "maxlength" => "255",
                "readonly"=>"readonly"])}}
        {{Form::text("email", $user->email, ["class"=>"form-control spacer-1em", "maxlength" => "255",
                "readonly"=>"readonly"])}}
      </div>
    </div>
    <div class="spacer clearfix"></div>
    <div class="spacer clearfix"></div>
    <div class="spacer clearfix"></div>
    
  </div>
@stop

app/views/controllers/ProfileController/getPayments.blade.php
@extends("layouts.base")

@section("content")
  <div class="container font-merriweather">
    <h4 class="spacer-1em">
      <b>{{ucfirst(t("profile.my_payments"))}}</b>
    </h4>
    <div class="row">
      <div class="col-sm-8 line-2">
        {{t("profile.my_payments_text")}}
      </div>
   </div>

   <div class="row spacer-2em info-list">
     <div class="col-md-12 col-lg-8"> <!--table-responsive-->
      <table class="table font-proxima"  id="payments">
        <thead>
          <tr><th class="slash">{{t("profile.invoice_number")}} </th>
              <th class="slash">{{t("profile.billing_date")}} </th>
              <th class="slash">{{t("profile.payment_due")}} </th>
              <th class="slash">{{t("profile.total_amount")}} </th>
              <th>{{t("profile.status")}} </th>
              <th></th>
              <th></th>
          </tr>
        </thead>
        <tbody>
         @foreach($payments as $payment)
           <tr><td>{{$payment->invoice_number}}</td>
              <td>{{date("d/m-Y", strtotime($payment->billing_date))}}</td>
              <td>{{date("d/m-Y", strtotime($payment->payment_due))}}</td>
              <td>{{$payment->total_amount_due . " ".t("profile.currency")}}</td>
              <td>{{strtoupper($payment->getStatus())}}</td>
              <td><a href="#" class="btn btn-default font-proxima width-100" role="button">
                   {{strtoupper(t("profile.receipt"))}}</a></td>
              <td><a href="#" class="btn btn-default font-proxima width-100" role="button">
                   {{strtoupper(t("profile.invoice"))}}</a></td>
           </tr>
          @endforeach
        </tbody>
      </table>
     </div>
    </div>
    <div class="row spacer-1em">
    </div> 
    
    
    
    <div class="spacer clearfix"></div>
    <div class="spacer clearfix"></div>
    <div class="spacer clearfix"></div>
    
  </div>
@stop